apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-frontend
  namespace: restaurantspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-frontend
  template:
    metadata:
      labels:
        app: restaurant-frontend
    spec:
      containers:
      - name: frontend
        image: yogeshpc2/restaurant-frontend
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_BASE_URL
          value: "http://restaurant-backend:8000"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"