apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: restaurantspace
spec:
  selector:
    app: restaurant-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
