apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restaurantpro
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:yogeshGit11/restaurantpro-gitops-infra.git'
    targetRevision: HEAD
    path: kubernetes/base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: restaurantspace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
