apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restaurant-postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yogeshGit11/restaurantpro-gitops-infra.git
    targetRevision: main
    path: kubernetes/base/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: restaurantspace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
