apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-backend
  namespace: restaurantspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-backend
  template:
    metadata:
      labels:
        app: restaurant-backend
    spec:
      containers:
      - name: backend
        image: yogeshpc2/restaurant-backend
        ports:
        - containerPort: 8000
        env:
        - name: DISABLE_CSRF_CHECKS
          value: "true"
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_USER
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_HOST
        - name: USE_POSTGRES
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: USE_POSTGRES
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_PASSWORD
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
